# fly.toml app configuration file generated for habit-api on 2025-06-24T21:23:53+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "habit-api"
primary_region = "arn"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[mounts]]
source = "habit_data_1"
destination = "/app/data"

[[services.http_checks]]
  interval = "10s"
  timeout = "2s"
  grace_period = "30s"
  method = "get"
  path = "/health"
  protocol = "http"
  port = 8080

[env]
  PORT = "8080"
  NODE_ENV = "production"

[services.concurrency]
  type = "connections"
  hard_limit = 25
  soft_limit = 20

[[vm]]
  memory = "256MB"
  cpu_kind = "shared"
  cpus = 1